# Generated by Django 3.2 on 2021-04-28 11:42

from django.db import migrations, models
import django.db.models.deletion
import rodo_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('training_email', models.EmailField(max_length=254)),
                ('number', models.CharField(default=rodo_app.models.url_generator, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('user_email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=16)),
                ('address', models.CharField(max_length=64)),
                ('post_code', models.CharField(max_length=6)),
                ('city', models.CharField(max_length=32)),
                ('consent_1', models.CharField(max_length=16)),
                ('consent_2', models.CharField(max_length=16)),
                ('consent_3', models.CharField(max_length=16)),
                ('user_url', models.CharField(default=rodo_app.models.url_generator, max_length=64)),
                ('email_confirmed', models.BooleanField(default=False)),
                ('training', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rodo_app.training')),
            ],
        ),
    ]
