# Generated by Django 3.2 on 2021-04-28 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rodo_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='training',
            old_name='number',
            new_name='training_url',
        ),
    ]
